version: '3'
services:
  build:
    build:
      context: .
    command: ls /source && bash /source/build.sh
    volumes:
      - /tmp/dist:/dist
    ports:
      - 2345:2345
    security_opt:
      - seccomp:unconfined

  test:
    build:
      context: .
    command: ./test/test.sh