version: '3'
services:
  build:
    build:
      context: .
    command: bash /source/build.sh linux
    volumes:
      - /tmp/dist:/dist

  test:
    build:
      context: .
    command: ./test/test.sh