version: '3'
services:
  build:
    build:
      context: .
    command: |
      go run tbx.go dev build info
      go build -o build/tbx .
    volumes:
      - /tmp/dist:/dist

  test:
    build:
      context: .
    command: go test -v -short -timeout 30s ./...

  docs:
    build:
      context: docs
    command: jekyll serve --config /srv/jekyll/source/_config.yml,/srv/jekyll/source/_config_dev.yml --watch --destination /srv/jekyll/staging --source /srv/jekyll/source --future
    volumes:
      - ./docs:/srv/jekyll/source
    ports:
      - "4000:4000"