version: 2
jobs:
  build_linux:
    docker:
      - image: techknowlogick/xgo:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
      - run: bash ./build.sh linux
      - store_artifacts:
          path: dist
      - save_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
          paths:
            - $HOME/go/pkg/mod

  build_linux_arm:
    docker:
      - image: techknowlogick/xgo:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
      - run: bash ./build.sh linux-arm
      - store_artifacts:
          path: dist
      - save_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
          paths:
            - $HOME/go/pkg/mod

  build_win:
    docker:
      - image: techknowlogick/xgo:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
      - run: bash ./build.sh win
      - store_artifacts:
          path: dist


  build_darwin:
    docker:
      - image: techknowlogick/xgo:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
      - run: bash ./build.sh darwin
      - store_artifacts:
          path: dist


  build_darwin_arm:
    docker:
      - image: techknowlogick/xgo:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: build-mod-{{ checksum "go.mod.sum" }}
      - run: bash ./build.sh darwin-arm
      - store_artifacts:
          path: dist


  test:
    docker:
      - image: cimg/go:1.19
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
      - run: mkdir -p test/results
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/jstemmer/go-junit-report
      - run: bash ./test/test.sh
      - save_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
          paths:
            - $HOME/go/pkg/mod
      - store_test_results:
          path: test/results
      - store_artifacts:
          path: test/results
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
      - build_linux_arm
      - build_win
      - build_darwin
      - build_darwin_arm
      - test
