version: 2
jobs:
  build:
    docker:
      - image: golang:1.16
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get github.com/google/go-licenses
      - run: ./build.sh
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/dist

  test:
    docker:
      - image: golang:1.16
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
      - run: apt-get install -y zip git curl jq
      - run: mkdir -p test/results
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/jstemmer/go-junit-report
      - run: ./test/test.sh
      - save_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: /go/src/github.com/watermint/toolbox/test/results
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/test/results
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
