# Permalinks
relative_permalinks: false

# About
title: watermint toolbox
tagline: "CLI tools for Dropbox and Dropbox Business"
description: 'Set of tool commands for Dropbox and Dropbox Business.'

url: 'https://watermint.github.io/toolbox'

# Url
paginate: 5

# Markdown
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Contact
author:
  name: Takayuki Okazaki
  url: https://github.com/watermint

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

# i18n
languages: ["en", "ja"]
exclude_from_localizations: ["favicon.ico", "images"]
defaultLang: en
languageNames:
  en: English
  ja: 日本語
