# Permalinks
relative_permalinks: false

# About
title: watermint toolbox
tagline: "CLI tools for Dropbox and Dropbox Business"
description: 'Set of tool commands for Dropbox and Dropbox Business.'

url: 'https://toolbox.watermint.org'

# Url
paginate: 5

# Markdown
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Contact
author:
  name: Takayuki Okazaki
  url: https://github.com/watermint

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
