
name: Test

on:
  push:
    branches: [ "main", "current" ]
  pull_request:
    branches: [ "current" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true

      - name: test
        run: ./test/test.sh
        env:
          RUN_NUMBER: '${{ github.run_number }}'
          TOOLBOX_DEPLOY_DB: '${{ secrets.TOOLBOX_DEPLOY_DB }}'
          TOOLBOX_REPLAY_URL: '${{ secrets.TOOLBOX_REPLAY_URL }}'
          TOOLBOX_SKIPENDTOENDTEST: true

      - name: upload coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'

